# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/pasir/Desktop/FPGA_Projects/Full_Adder/CLK/CLK.srcs/sources_1/ip/div_gen_1/div_gen_1.xci
# IP: The module: 'div_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pasir/Desktop/FPGA_Projects/Full_Adder/CLK/CLK.gen/sources_1/ip/div_gen_1/div_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/pasir/Desktop/FPGA_Projects/Full_Adder/CLK/CLK.srcs/sources_1/ip/div_gen_1/div_gen_1.xci
# IP: The module: 'div_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pasir/Desktop/FPGA_Projects/Full_Adder/CLK/CLK.gen/sources_1/ip/div_gen_1/div_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
